//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/t4models).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------
using System;
using System.Linq;

using LinqToDB;
using LinqToDB.Mapping;

namespace ES1.Models
{
	/// <summary>
	/// Database       : cities
	/// Data Source    : localhost
	/// Server Version : 5.7.21-log
	/// </summary>
	public partial class CitiesDB : LinqToDB.Data.DataConnection
	{
		public ITable<CitiesData> CitiesData { get { return this.GetTable<CitiesData>(); } }

		public CitiesDB()
		{
			InitDataContext();
		}

		public CitiesDB(string configuration)
			: base(configuration)
		{
			InitDataContext();
		}

		partial void InitDataContext();
	}

	[Table("cities_data")]
	public partial class CitiesData
	{
		[Column(),                            NotNull] public char   Nhemisphere   { get; set; } // varchar(1)
		[Column(),                            NotNull] public char   Whemisphere   { get; set; } // varchar(1)
		[Column("continent"),                 NotNull] public string Continent     { get; set; } // varchar(45)
		[Column("posContWEC"),                NotNull] public string PosContWEC    { get; set; } // varchar(45)
		[Column("posContSNC"),                NotNull] public string PosContSNC    { get; set; } // varchar(45)
		[Column("country"),                   NotNull] public string Country       { get; set; } // varchar(255)
		[Column("posCountryWEC"),             NotNull] public string PosCountryWEC { get; set; } // varchar(45)
		[Column("posCountrySNC"),             NotNull] public string PosCountrySNC { get; set; } // varchar(45)
		[Column("population"),                NotNull] public string Population    { get; set; } // varchar(45)
		[Column("posBySea"),                  NotNull] public char   PosBySea      { get; set; } // varchar(1)
		[Column("name"),          PrimaryKey, NotNull] public string Name          { get; set; } // varchar(255)
	}

	public static partial class TableExtensions
	{
		public static CitiesData Find(this ITable<CitiesData> table, string Name)
		{
			return table.FirstOrDefault(t =>
				t.Name == Name);
		}
	}
}
